AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Launch a static website backed by an S3 bucket and served via http through cloudfront.
  Assumes you have the following available already:
  * An address for the website in mind (e.g. blog.example.com)
  * An existing Route53 Hosted Zone for the domain

Parameters:
  HostedZoneName:
    Description: >
      The Hosted Zone in which to create the website's DNS record. e.g. mycodefu.com.
    Type: "String"
  WebsiteAddress:
    Description: >
      The web address to host the website at. Must be a subdomain of the hostedzone. e.g. cfn-cf.mycodefu.com
    Type: "String"
  S3BucketName:
    Description: Name of the s3 bucket to create for website source files. e.g. cfn-cf-site
    Type: "String"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          -
            Sid: "AllowAll"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: "S3Bucket"
                  - "/*"
            Principal: "*"
  R53Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment:
        Fn::Join:
          - ""
          -
            - "Alias CloudFront for "
            -
              Ref: "WebsiteAddress"
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref WebsiteAddress
      Type: CNAME
      ResourceRecords:
        - !GetAtt CFDistribution.DomainName
      SetIdentifier: CDN_OLD
      Weight: 0
      TTL: 60
  CFDistribution:
    Type: "AWS::CloudFront::Distribution"
    DependsOn: "S3Bucket"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref WebsiteAddress
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            OriginPath: ""
            Id: S3BucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        Comment:
          Fn::Join:
            - ""
            -
              - "CloudFront origin for "
              -
                Ref: "WebsiteAddress"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3BucketOrigin
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: "true"
        PriceClass: "PriceClass_All"

Outputs:
  WebsiteAddress:
    Description: Published website address!
    Value:
      Fn::Join:
        - ""
        -
          - "http://"
          -
            Ref: "WebsiteAddress"
  S3DirectURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3