AWSTemplateFormatVersion: "2010-09-09"

Description: Transition between two CDNs using Route53 Weighted DNS

Parameters:
  HostedZoneName:
    Description: >
      The Hosted Zone in which to create the website's DNS record. e.g. mycodefu.com.
    Type: "String"
  WebsiteAddress:
    Description: The web address of the website. Must be a subdomain of the hostedzone. e.g. cfn.mycodefu.com
    Type: "String"
  LegacyCDNDomain:
    Description: The DNS of the legacy CDN.
    Type: "String"
  LegacyCDNDomainWeight:
    Default: '100'
    Description: The DNS record weight value for the legacy CDN
    Type: String
  CDNDomain:
    Description: The DNS of the CDN.
    Type: "String"
  CDNDomainWeight:
    Default: '0'
    Description: The DNS record weight value for the CDN
    Type: String

Conditions:
  CreateLegacyCDN: !Not [!Equals [!Ref LegacyCDNDomainWeight, 0]]
  CreateCDN: !Not [!Equals [!Ref CDNDomainWeight, 0]]

Resources:
  LegacyCDNR53Record:
    Type: "AWS::Route53::RecordSet"
    Condition: CreateLegacyCDN
    Properties:
      Name: !Ref 'WebsiteAddress'
      HostedZoneName: !Ref 'HostedZoneName'
      ResourceRecords:
        - !Ref 'LegacyCDNDomain'
      SetIdentifier: LegacyCDN
      TTL: 10
      Type: CNAME
      Weight: !Ref 'LegacyCDNDomainWeight'
  CDNR53Record:
    Type: "AWS::Route53::RecordSet"
    Condition: CreateCDN
    Properties:
      Name: !Ref 'WebsiteAddress'
      HostedZoneName: !Ref 'HostedZoneName'
      ResourceRecords:
      - !Ref 'CDNDomain'
      TTL: 10
      SetIdentifier: CDN
      Type: CNAME
      Weight: !Ref 'CDNDomainWeight'

Outputs:
  WebsiteAddress:
    Description: Website address
    Value: !Ref "WebsiteAddress"
  LegacyCDNDomain:
    Value: !Ref LegacyCDNDomain
    Description: Legacy CDN domain name
  CloudFrontCDNDomain:
    Value: !Ref CDNDomain
    Description: CloudFront CDN domain name
  PercentTransitioned:
    Description: Percentage transitioned to CDN
    Value: !Ref "CDNDomainWeight"